### ISSUE TITLE
Emit ES2015 and UMD bundles

### ISSUE THREAD

**Issue by Eddman** [Herbis/ngx-modal#1]
Currently ngx-modal delivery contains AMD and System bundles. 

Add also ES2015 bundles to allow tree-shaking.

Also UMD bundle will be better as AMD. Some tools do not support AMD, but support CommonJS only.

**Comment by Eddman** [comment]
The desired structure should be (see for instance https://github.com/angular/material2):
```
- @herbis/ 
    - ngx-modal.xyz.js (at least UMD and ES bundles, CommonJS is also good)
- index.d.ts
- index.metadata.json
(no .js or .js.map)
package.json
```

`package.json` should contain the following entries:
```
{
  "main": "./@herbis/ngx-modal.umd.js", (for all UMD)
  "module": "./@herbis/ngx-modal.es.js", (ES 2015 for tree-shaking tools)
  "es2015": "./@herbis/ngx-modal.es.js", (ES 2015 for tree-shaking tools)
  "types": "./index.d.ts"
  "typings": "./index.d.ts"
}
```

This config will allow correct AOT, tree-shaking, dynamic browser usage...

**Comment by Herbis** [comment]
Feel free to fork the project and create a pull request, if you wish to see this implemented.
I did look into implementing this, but it seems a bit too difficult for me, as I lack the knowledge on bundling and don't think I would be able to test it myself. Sorry.
