### ISSUE TITLE
Modal in different component

### ISSUE THREAD

**Issue by SravaniGunda** [Herbis/ngx-modal#2]
In the examples provided button and modal are in same component.
Is it possible to have button in parent component and modal in child component?

**Comment by Herbis** [comment]
Sorry for the delay, for some reason I don't get notifications of the issues.

Yes, you would just have to remove at least the button labels, so that the buttons don't get added.
```
cancelButtonLabel="cancel"
submitButtonLabel="submit"
```
And add your own buttons wherever you need them, with your own logic:
```
<button class="btn btn-default" data-dismiss="modal" type="button" (click)="close()">Close</button>
<button class="btn btn-primary" type="button" (click)="submit()">Submit</button>
```
