### ISSUE TITLE
Incompatible with Angular 8+

### ISSUE THREAD

**Issue by nicholas-heger-zirous** [Herbis/ngx-modal#6]
Because of some changes in Angular, projects using this package who use Angular 8+ will see an error preventing their apps from building. It would be ideal if there was a new version published that is compatible with Angular 8+.

**Comment by nicholas-heger-zirous** [comment]
I've opened up a pull request to resolve this problem: https://github.com/Herbis/ngx-modal/pull/5

**Comment by Herbis** [comment]
Thanks @nicholas-heger-zirous I will check it out.

**Comment by Herbis** [comment]
@nicholas-heger-zirous 
Well, this is not a simple process at all. Anyway, since I don't really have a way to test it, I published a beta package. Let me know if it works, or if doesn't work, please:
8.0.0-beta1

**Comment by Herbis** [comment]
I have now published a version 8.0.1 that works with angular 8+.
